x = input('Digite algo: ')
print('O tipo primitivo de {} é '.format(x), type(x))
print('{} tem só espaços? '.format(x), x.isspace())
print('{} é um número? '.format(x), x.isnumeric())
print('{} é uma palavra?'.format(x), x.isalpha())
print('{} tem letras e números?'.format(x), x.isalnum())
print('{} está em maiúsculas?'.format(x), x.isupper())
print('{} está em minúsculas?'.format(x), x.islower())
print('{} está capitalizada?'.format(x), x.istitle())